'use client';
import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { Dice1,Dice2,Dice3,Dice4,Dice5,Dice6,Dices,Layers,House,TrendingUp,ArrowUpRight,Sparkles,Plus,Check,Users,History,Trophy,ChevronDown,ArrowRight,RotateCcw,Copy,LoaderCircle,Download,Star,NotebookPen,Flag,Monitor,LogIn,LogOut } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Table,TableHeader,TableHead,TableRow,TableBody,TableCell } from '@/components/ui/table';
import { Toaster,toast } from 'sonner';
import { categories,totals,leaderboard,type Category,type State,type Game } from '@/lib/game';
import { signInWithGoogle,signOutGoogle,syncGoogleProfile,watchGoogleAccount,type GoogleAccount } from '@/lib/firebase-profile';
const icons=[Dice1,Dice2,Dice3,Dice4,Dice5,Dice6,Layers,Layers,House,TrendingUp,ArrowUpRight,Star,Dices];
const fmtTime=(n:number)=>new Date(n).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const fmtDate=(n:number)=>new Date(n).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'});
function Count({value,duration=120}:{value:number;duration?:number}){const [display,setDisplay]=useState(value);const previous=useRef(value);useEffect(()=>{const from=previous.current;previous.current=value;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setDisplay(value);return}let frame=0;const start=performance.now();function tick(time:number){const p=Math.min((time-start)/duration,1);setDisplay(Math.round(from+(value-from)*p));if(p<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value,duration]);return <>{display}</>}
function Avatar({name}:{name:string}){return <span className="avatar">{name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase()}</span>}
function Empty({kind,title,body,action}:{kind:'history'|'trophy';title:string;body:string;action?:React.ReactNode}){const Icon=kind==='history'?History:Trophy;return <div className="empty-card"><Icon size={35} strokeWidth={1.4}/><h2>{title}</h2><p>{body}</p>{action}</div>}
type UndoAction={kind:'score';category:string;value:number|null;bonus:number;gameId:string;revision:number}|{kind:'bonus';bonus:number;gameId:string;revision:number};
export default function Home(){
 const [state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[tab,setTab]=useState('sheet');
 const [category,setCategory]=useState<Category|null>(null),[numeric,setNumeric]=useState(''),[openOnly,setOpenOnly]=useState(false),[tableOpen,setTableOpen]=useState(false);
 const [modal,setModal]=useState<'family'|'profile'|'new'|'finish'|null>(null),[profileName,setProfileName]=useState(''),[tableName,setTableName]=useState('Family game night'),[joinCode,setJoinCode]=useState('');
 const [celebrating,setCelebrating]=useState(false),[phase,setPhase]=useState(0),[lastUndo,setLastUndo]=useState<UndoAction|null>(null),[googleUser,setGoogleUser]=useState<GoogleAccount|null>(null),[authBusy,setAuthBusy]=useState(false);
 const token=useRef(''),snapshot=useRef<State|null>(null),busyRef=useRef(false),seq=useRef(0),celebrateTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const me=state?.me,game=state?.game,sheet=game?.sheets.find(s=>s.player_id===me?.id),score=totals(sheet?.scores,sheet?.bonus),host=state?.room.host_id===me?.id,mode=state?.mode==='lan';
 const celebrate=useCallback(()=>{setCelebrating(false);requestAnimationFrame(()=>setCelebrating(true));if(celebrateTimer.current)clearTimeout(celebrateTimer.current);celebrateTimer.current=setTimeout(()=>setCelebrating(false),2700);if(typeof navigator!=='undefined'&&navigator.vibrate)navigator.vibrate([50,50,80]);},[]);
 const api=useCallback(async(data:Record<string,unknown>,quiet=false):Promise<State|null>=>{
  if(!token.current)return null;if(busyRef.current)return null;
  if(!quiet){busyRef.current=true;setBusy(true)}const requestSeq=++seq.current;
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);
  try{const response=await fetch('/api/game',{signal:controller.signal,method:'POST',headers:{'Content-Type':'application/json','x-player-token':token.current},body:JSON.stringify(data)});const next=await response.json() as State & {error?:string};if(!response.ok){if(response.status===409){setTimeout(()=>{void refreshRef.current()},100)}throw new Error(next.error||'Your score could not be saved. Try again.')}if(requestSeq===seq.current){snapshot.current=next;setState(next);setError('');setReady(true)}return next;
  }catch(e){if(requestSeq===seq.current){setError(e instanceof Error&&e.name!=='AbortError'?e.message:'Connection lost. Your input is still here. Please try again.');setReady(true)}return null;
  }finally{clearTimeout(timeout);if(!quiet){busyRef.current=false;setBusy(false)}}
 },[]);
 const refreshRef=useRef<()=>Promise<unknown>>(async()=>{});refreshRef.current=()=>api({action:'refresh'},true);
 useEffect(()=>{try{let saved=localStorage.getItem('yahtzee-player-key');if(!saved){saved=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');localStorage.setItem('yahtzee-player-key',saved)}token.current=saved}catch{setError('Allow browser storage so this device can remember your player.');setReady(true);return}
  const code=new URLSearchParams(window.location.search).get('table');if(code){setJoinCode(code);setModal('family')}
  void api({action:'bootstrap'});const timer=setInterval(()=>{if(document.visibilityState==='visible')void api({action:'refresh'},true)},4000);const reconnect=()=>void api({action:'bootstrap'},true);window.addEventListener('online',reconnect);return()=>{clearInterval(timer);window.removeEventListener('online',reconnect);if(celebrateTimer.current)clearTimeout(celebrateTimer.current)};
 },[api]);
 useEffect(()=>{if(mode)return;let stopped=false,unsubscribe:(()=>void)|undefined;void watchGoogleAccount(async user=>{if(stopped)return;setGoogleUser(user);if(!user)return;try{setAuthBusy(true);const accountToken=await syncGoogleProfile(user,token.current);token.current=accountToken;localStorage.setItem('yahtzee-player-key',accountToken);const next=await api({action:'bootstrap'});if(next?.me.name==='You'&&user.displayName)await api({action:'rename',name:user.displayName.slice(0,32)});}catch(e){setError(e instanceof Error?e.message:'Google sign-in could not finish.');}finally{setAuthBusy(false)}}).then(stop=>{unsubscribe=stop}).catch(e=>setError(e instanceof Error?e.message:'Google sign-in could not load.'));return()=>{stopped=true;unsubscribe?.()}},[api,mode]);
 useEffect(()=>{if(modal!=='finish')return;setPhase(0);const timers=[600,1200,1900,2500].map((ms,i)=>setTimeout(()=>{setPhase(i+1);if(i===3)celebrate()},ms));return()=>timers.forEach(clearTimeout)},[modal,celebrate]);
 useEffect(()=>{if(game?.id){setLastUndo(null);setCategory(null);setOpenOnly(false)}},[game?.id]);
 async function saveScore(c:Category,value:number|null,undo=false,restoreBonus?:number){if(!game||!sheet||!state)return;if(c.id==='yahtzee'&&value===50&&sheet.scores.yahtzee===50&&!undo){setCategory(null);setNumeric('');await changeBonus(sheet.bonus+1);return}const previous=state,old=sheet.scores[c.id]??null,oldBonus=sheet.bonus,before=score.filled,nextBonus=c.id==='yahtzee'?(value===50?(restoreBonus??sheet.bonus):0):sheet.bonus;const updateGame=(g:Game):Game=>g.id!==game.id?g:{...g,sheets:g.sheets.map(s=>s.player_id===me?.id?{...s,scores:{...s.scores,[c.id]:value},bonus:nextBonus}:s)};setState({...state,game:updateGame(state.game),history:state.history.map(updateGame)});setCategory(null);setNumeric('');const next=await api({action:'score',gameId:game.id,category:c.id,value,revision:sheet.revision,...(restoreBonus!==undefined?{restoreBonus}: {})});if(!next){setState(previous);return}const own=next.game.sheets.find(s=>s.player_id===next.me.id)!;if(undo)setLastUndo(null);else setLastUndo({kind:'score',category:c.id,value:old,bonus:oldBonus,gameId:game.id,revision:own.revision});if(before<13&&totals(own.scores,own.bonus).filled===13)setModal('finish');else if(c.id==='yahtzee'&&value===50&&old!==50)celebrate();}
 async function changeBonus(nextBonus:number,undo=false){if(!sheet||!game||!state||nextBonus<0||nextBonus>12)return;const previous=state,oldBonus=sheet.bonus,updateGame=(g:Game):Game=>g.id!==game.id?g:{...g,sheets:g.sheets.map(s=>s.player_id===me?.id?{...s,bonus:nextBonus}:s)};setState({...state,game:updateGame(state.game),history:state.history.map(updateGame)});const next=await api({action:'bonus',gameId:game.id,bonus:nextBonus,revision:sheet.revision});if(!next){setState(previous);return}const own=next.game.sheets.find(s=>s.player_id===next.me.id)!;if(undo)setLastUndo(null);else setLastUndo({kind:'bonus',bonus:oldBonus,gameId:game.id,revision:own.revision});if(nextBonus>oldBonus){celebrate();toast.success('+100 Yahtzee bonus');}}
 async function undo(){if(!lastUndo||!sheet)return;if(sheet.revision!==lastUndo.revision){setLastUndo(null);toast('Your sheet changed somewhere else. Tap the category to edit it.');return}if(lastUndo.kind==='bonus'){await changeBonus(lastUndo.bonus,true);return}const c=categories.find(c=>c.id===lastUndo.category)!;await saveScore(c,lastUndo.value,true,lastUndo.bonus)}
 async function beginNewGame(){if(!game||!host)return;const next=await api({action:'new-game',gameId:game.id,confirm:true});if(next){setModal(null);setTab('sheet');toast.success('New game started.')}}
 function requestNewGame(){if(!game||!host||busy)return;if(game.ended_at)void beginNewGame();else setModal('new')}
 async function copyCode(link=false){if(!state)return;const value=link?`${window.location.origin}/?table=${state.room.code}`:state.room.code;try{await navigator.clipboard.writeText(value);toast.success(link?'Table link copied':'Table code copied')}catch{toast('Select and copy your table code below.')}}
 const live=game?[...game.sheets].sort((a,b)=>totals(b.scores,b.bonus).total-totals(a.scores,a.bonus).total):[];
 const played=state?.history.filter(g=>g.ended_at)||[],leaders=leaderboard(state?.history||[]),best=played.length?Math.max(...played.flatMap(g=>g.sheets.map(s=>totals(s.scores,s.bonus).total))):0;
 const groups=(state?.history||[]).filter(g=>g.id!==game?.id||g.ended_at).reduce<Record<string,Game[]>>((acc,g)=>{const key=fmtDate(g.started_at);(acc[key]??=[]).push(g);return acc},{});
 function row(c:Category,i:number){const val=sheet?.scores[c.id],filled=val!==null&&val!==undefined,Icon=icons[i];return <button key={c.id} className={`score-row ${filled?'filled':''} ${val===0?'zero':''} ${openOnly&&filled?'hidden-row':''}`} disabled={!sheet||busy} aria-label={`${c.name}, ${filled?`${val} points. Edit score`:'not scored. Enter score'}`} onClick={()=>{setCategory(c);setNumeric(filled?String(val):'')}}><span className="score-icon"><Icon strokeWidth={1.5}/></span><span className="row-label">{c.name}</span><span key={`${c.id}-${val}-${sheet?.bonus||0}`} className="score-value">{filled?val:<Plus size={15} strokeWidth={1.4}/>}</span></button>}
 return <div className="app"><Toaster position="top-center" richColors/><header className="topbar"><div className="brand"><span className="brand-icon"><Dice5 size={28} strokeWidth={1.7}/></span><span>Yahtzee</span></div><div className="header-right"><button className="profile-btn" onClick={()=>{setProfileName(me?.name==='You'?'':me?.name||'');setModal('profile')}}><Avatar name={googleUser?.displayName||me?.name||'You'}/><span>{googleUser?.displayName||me?.name||'You'}</span>{googleUser?<ChevronDown size={13}/>:<LogIn size={13}/>}</button></div></header>
 <main className="shell"><Tabs value={tab} onValueChange={setTab} className="app-tabs"><TabsList className="nav-tabs" aria-label="App views"><TabsTrigger value="sheet"><NotebookPen size={17}/>Score sheet</TabsTrigger><TabsTrigger value="leaderboard"><Trophy size={17}/>Leaderboard</TabsTrigger><TabsTrigger value="history"><History size={17}/>Game history</TabsTrigger></TabsList>
 {error&&<div role="alert" className="inline-error sync-banner">{error} <button className="text-btn" onClick={()=>void api({action:'bootstrap'})}>Reconnect</button></div>}
 <TabsContent value="sheet"><div className="compact-head"><span>{game?`Game ${state?.history.length.toString().padStart(2,'0')} · ${fmtTime(game.started_at)}`:'New game'}</span><button className="btn small" disabled={!state||!host||busy} onClick={requestNewGame}><Plus size={15}/>New game</button></div>
 {state&&!sheet&&<p className="inline-error" style={{marginBottom:16}}>This game is already finished. The host can start a new game to give you a score sheet.</p>}<div className="game-grid"><section className="sheet"><div className="sheet-head"><h2>{me?.name&&me.name!=='You'?`${me.name}’s`:'Your'} score sheet</h2><button className={`pill filter ${openOnly?'':'neutral'}`} aria-pressed={openOnly} onClick={()=>setOpenOnly(!openOnly)}>{openOnly?<Check size={12}/>:null}{score.remaining} left {openOnly?'· show all':<ChevronDown size={12}/>}</button></div>
 <div className="score-columns"><div className="score-section"><div className="section-label">Upper section <span>01—06</span></div>{categories.slice(0,6).map((c,i)=>row(c,i))}<div className="bonus-box"><div className="bonus-top"><span className="inline" style={{gap:5}}><Sparkles size={12}/>Bonus</span><strong>{score.upper} / 63</strong></div><Progress className="bonus-progress" aria-label="Upper bonus progress" value={Math.min(score.upper/63*100,100)}/></div><div className="subtotal"><span>Upper total</span><strong><Count value={score.upperTotal}/></strong></div></div>
 <div className="score-section"><div className="section-label">Lower section <span>07—13</span></div>{categories.slice(6).map((c,i)=>row(c,i+6))}<div className="yahtzee-bonus"><span className="inline" style={{gap:4}}><Sparkles size={13}/>Yahtzee bonus</span><strong>{(sheet?.bonus||0)*100}</strong></div><div className="subtotal"><span>Lower total</span><strong><Count value={score.lower}/></strong></div></div></div>
 <div className="sheet-foot"><span>{busy?<LoaderCircle size={13} className="spinner"/>:<Check size={13}/>} {busy?'Saving…':state?'Saved':ready?'Offline':'Opening…'}</span><button className="text-btn" disabled={!lastUndo||busy} onClick={()=>void undo()}><RotateCcw size={12}/>Undo</button></div></section>
 <aside className="side"><section className={`total-card ${score.remaining===0?'complete':''}`}><div className="eyebrow">Final score</div><div className="total-number"><Count value={score.total}/><span>pts</span></div><div className="total-breakdown"><div><span>Upper</span><strong><Count value={score.upper}/></strong></div><div><span>Bonus</span><strong>{score.upperBonus?'+35':'—'}</strong></div><div><span>Lower</span><strong><Count value={score.lower}/></strong></div></div><Progress className="game-progress" aria-label="Categories completed" value={score.filled/13*100}/></section>
 <div className="celebrate-wrap"><button className="celebrate-btn" onClick={celebrate}><Sparkles size={20}/>YAHTZEE!<Sparkles size={20}/></button></div>
 <section className={`table-card ${tableOpen?'open':''}`}><button className="card-heading table-toggle" aria-expanded={tableOpen} onClick={()=>setTableOpen(!tableOpen)}><h2>{state?.room.name||'My table'}</h2><span className="pill neutral">{live.length||1} {live.length===1?'player':'players'} <ChevronDown size={13}/></span></button><div className="table-body">{live.map((s,i)=><div className="player-row" key={s.player_id}><span className="player-rank">{i+1}</span><Avatar name={s.name}/><span className="player-name">{s.name}{s.player_id===me?.id&&s.name!=='You'?' (you)':''}<small>{s.completed_at?'Finished':`${totals(s.scores,s.bonus).remaining} left`}</small></span><span className="player-score"><Count value={totals(s.scores,s.bonus).total}/></span></div>)}<div className="listening"><span/>Listening · {state?.players.filter(p=>p.active).length||1} here</div><button className="btn" onClick={()=>setModal('family')} disabled={!state}><Plus size={15}/>Invite player</button>{score.filled===13&&<button className="btn primary" onClick={()=>setModal('finish')}><Trophy size={15}/>Final score</button>}</div></section></aside></div>
 </TabsContent>
 <TabsContent value="leaderboard"><div className="intro"><h1>Leaderboard</h1><button className="btn" onClick={()=>setModal('family')} disabled={!state}><Users size={16}/>Change table</button></div><div className="leader-stats"><div className="stat-box"><small>Games</small><strong>{played.length.toString().padStart(2,'0')}</strong></div><div className="stat-box"><small>High score</small><strong>{best||'—'}</strong></div><div className="stat-box"><small>Players</small><strong>{leaders.length||live.length||'—'}</strong></div></div>{leaders.length?<div className="leader-table"><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Player</TableHead><TableHead>Wins</TableHead><TableHead>Best</TableHead><TableHead>Average</TableHead><TableHead>Games</TableHead></TableRow></TableHeader><TableBody>{leaders.map((p,i)=><TableRow key={p.id}><TableCell>{i===0&&p.wins?<Trophy size={18} color="#9a883a"/>:i+1}</TableCell><TableCell><span className="name-cell"><Avatar name={p.name}/>{p.name}</span></TableCell><TableCell><strong>{p.wins}</strong></TableCell><TableCell>{p.best}</TableCell><TableCell>{Math.round(p.sum/p.games)}</TableCell><TableCell>{p.games}</TableCell></TableRow>)}</TableBody></Table></div>:<Empty kind="trophy" title="No completed games" body="Finish a game to start the leaderboard." action={<button className="btn primary" onClick={()=>setTab('sheet')}>Score sheet<ArrowRight size={15}/></button>}/>}</TabsContent>
 <TabsContent value="history"><div className="intro"><h1>Game history</h1><button className="btn" onClick={()=>setModal('family')} disabled={!state}><Users size={16}/>Change table</button></div><div className="history-layout">{Object.keys(groups).length?Object.entries(groups).map(([day,gs])=><section key={day}><h2 className="history-date">{day}</h2>{gs.map(g=><HistoryCard key={g.id} game={g} />)}</section>):<Empty kind="history" title="No games yet" body="Finished games appear here." action={<button className="btn primary" onClick={()=>setTab('sheet')}>Score sheet<ArrowRight size={15}/></button>}/>}</div></TabsContent>
 </Tabs></main>
 <Dialog open={!!category} onOpenChange={open=>{if(!open&&!busy){setCategory(null);setNumeric('')}}}><DialogContent className="modal" onCloseAutoFocus={e=>e.preventDefault()}><DialogHeader><DialogTitle>{category?.name}</DialogTitle><DialogDescription>{category&&'face'in category?`How many ${category.name.toLowerCase()} did you roll?`:category?.hint}</DialogDescription></DialogHeader>
 {error&&<div className="inline-error" role="alert">{error}</div>}
 {category&&'face'in category?<div className="choices">{[0,1,2,3,4,5].map(n=><button disabled={busy} key={n} className={`choice ${n===0?'zero-choice':''}`} onClick={()=>void saveScore(category,n*category.face)}>{n*category.face}<small>{n===0?'Cross out':`${n} ${n===1?'die':'dice'}`}</small></button>)}</div>:category&&'fixed'in category?<div className="choices fixed-scores"><button disabled={busy} className="choice zero-choice" onClick={()=>void saveScore(category,0)}>0<small>Cross out</small></button><button disabled={busy} className="choice" onClick={()=>void saveScore(category,category.fixed)}>{category.fixed}<small>Score it</small></button></div>:<form onSubmit={e=>{e.preventDefault();if(category&&numeric.trim()&&Number(numeric)>=5&&Number(numeric)<=30)void saveScore(category,Number(numeric))}}><label className="field-label" htmlFor="score-input">Total of all five dice (5–30)</label><input id="score-input" className="number-input" inputMode="numeric" type="number" min={5} max={30} step={1} autoFocus value={numeric} onChange={e=>setNumeric(e.target.value)} placeholder="0"/><div className="actions" style={{marginTop:14}}><button className="btn" type="button" disabled={busy} onClick={()=>category&&void saveScore(category,0)}>Cross out · 0</button><button className="btn primary" disabled={busy||!numeric.trim()||Number(numeric)<5||Number(numeric)>30||!Number.isInteger(Number(numeric))} type="submit">{busy?'Saving…':'Save score'}<Check size={16}/></button></div></form>}
 {category&&sheet?.scores[category.id]!=null&&<button className="btn clear-category" disabled={busy} onClick={()=>void saveScore(category,null)}><RotateCcw size={15}/>Clear category</button>}</DialogContent></Dialog>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal(null)}}><DialogContent className="modal">
 {modal==='profile'&&<><DialogHeader><DialogTitle>Profile</DialogTitle></DialogHeader>{!mode&&<div className="google-auth">{googleUser?<><div className="google-account"><Avatar name={googleUser.displayName||googleUser.email||'G'}/><span><strong>{googleUser.displayName||'Google account'}</strong><small>{googleUser.email}</small></span></div><button className="btn" disabled={authBusy} onClick={async()=>{try{setAuthBusy(true);await signOutGoogle();setGoogleUser(null)}catch(e){setError(e instanceof Error?e.message:'Could not sign out.')}finally{setAuthBusy(false)}}}><LogOut size={15}/>Sign out</button></>:<button className="btn google-btn" disabled={authBusy} onClick={async()=>{try{setAuthBusy(true);await signInWithGoogle()}catch(e){setError(e instanceof Error?e.message:'Google sign-in was canceled.')}finally{setAuthBusy(false)}}}><span className="google-g">G</span>{authBusy?'Opening Google…':'Sign in with Google'}</button>}</div>}<form className="section-divider" onSubmit={async e=>{e.preventDefault();const next=await api({action:'rename',name:profileName});if(next)setModal(null)}}><label className="field-label" htmlFor="player-name">Player name</label><input id="player-name" className="field" autoFocus maxLength={32} placeholder="David" value={profileName} onChange={e=>setProfileName(e.target.value)} required/><button className="btn primary" style={{width:'100%',marginTop:15}} disabled={busy||!profileName.trim()}>Save<Check size={16}/></button></form></>}
 {modal==='family'&&<><DialogHeader><p className="eyebrow">Better together</p><DialogTitle>Your family table</DialogTitle><DialogDescription>{mode?'Everyone opens the address shown on the host computer, then joins with this code.':'Share your table link and code. Everyone scores on their own phone.'}</DialogDescription></DialogHeader>{me?.name==='You'&&<button className="btn" onClick={()=>{setProfileName('');setModal('profile')}}>First, add your name<ArrowRight size={15}/></button>}{state&&<><div className="room-code">{state.room.code}</div><div className="actions"><button className="btn" onClick={()=>void copyCode()}><Copy size={15}/>Copy code</button><button className="btn primary" onClick={()=>void copyCode(true)}><Copy size={15}/>Copy table link</button></div></>}
 <form className="section-divider" onSubmit={async e=>{e.preventDefault();const next=await api({action:'join-room',code:joinCode});if(next){setModal(null);setJoinCode('');setTab('sheet');toast.success('You’re at the table.')}}}><label className="field-label" htmlFor="join-code">Table code</label><div className="inline"><input id="join-code" className="field" placeholder="ABCD" autoCapitalize="characters" autoCorrect="off" maxLength={8} value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())}/><button className="btn primary" disabled={busy||![4,8].includes(joinCode.replace(/[^a-z0-9]/gi,'').length)}>Join<ArrowRight size={14}/></button></div></form>
 {error&&<div role="alert" className="inline-error">{error}</div>}
 <form className="section-divider" onSubmit={async e=>{e.preventDefault();const next=await api({action:'create-room',name:tableName});if(next){toast.success('Your new table is ready. Share the code above.');setTab('sheet')}}}><label className="field-label" htmlFor="table-name">Start a separate table</label><div className="inline"><input className="field" id="table-name" value={tableName} onChange={e=>setTableName(e.target.value)} maxLength={32} required/><button className="btn" disabled={busy||!tableName.trim()}>Create</button></div></form>
 {state&&state.rooms.length>1&&<div className="room-list section-divider"><h3 className="field-label">Your tables</h3>{state.rooms.map(r=><button key={r.id} className="btn" disabled={busy||r.id===state.room.id} onClick={async()=>{if(await api({action:'switch-room',roomId:r.id})){setModal(null);setTab('sheet')}}}>{r.name}{r.id===state.room.id?<Check size={14}/>:<ArrowRight size={14}/>}</button>)}</div>}
 <div className="section-divider"><h3 className="modal-subheading inline"><Monitor size={16}/>{mode?'Playing on Wi-Fi only':'Want Wi-Fi-only play?'}</h3><p className="install-note" style={{marginTop:8}}>{mode?'Keep the host computer awake. Scores and game history are saved in its local database.':'The online version needs internet and Site access for each player. For private, internet-free play, run the local edition on one computer and connect everyone to the same Wi-Fi.'}</p>{!mode&&<a className="btn" style={{marginTop:12,width:'100%'}} href="/yahtzee-local.zip" download><Download size={15}/>Download the local edition</a>}</div></>}
 {modal==='new'&&<><DialogHeader><DialogTitle>Start a new game?</DialogTitle><DialogDescription>This game isn’t finished. Starting over will save it as unfinished.</DialogDescription></DialogHeader><div className="actions"><button className="btn" onClick={()=>setModal(null)}>Cancel</button><button className="btn primary" disabled={busy||!host} onClick={()=>void beginNewGame()}>Start new game<ArrowRight size={15}/></button></div>{error&&<p className="inline-error">{error}</p>}</>}
 {modal==='finish'&&<><DialogHeader><p className="eyebrow">That’s a wrap</p><DialogTitle>Every point, counted.</DialogTitle><DialogDescription>{me?.name==='You'?'Your':`${me?.name}’s`} final score · {game?fmtDate(game.started_at):''}</DialogDescription></DialogHeader><div><div className="finish-line"><span>Upper section</span><strong><Count value={score.upper}/></strong></div>{phase>=1&&<div className="finish-line"><span>Upper bonus</span><strong>{score.upperBonus?'+35':'0'}</strong></div>}{phase>=2&&<div className="finish-line"><span>Lower section {sheet?.bonus?'(includes Yahtzee bonus)':''}</span><strong><Count value={score.lower}/></strong></div>}</div><div className="finish-score"><p>GRAND TOTAL</p><strong><Count value={phase>=3?score.total:0} duration={700}/></strong></div><p className="install-note">{game?.ended_at?'Saved with everyone’s scores in game history.':'Your score is saved. The table result will be final when everyone finishes.'}</p><div className="actions"><button className="btn" onClick={()=>{setModal(null);setTab('history')}}>Game history</button>{host?<button className="btn primary" onClick={requestNewGame}>Play again<ArrowRight size={15}/></button>:<button className="btn primary" onClick={()=>setModal(null)}>Back to the table</button>}</div></>}
 </DialogContent></Dialog>
 {celebrating&&<div className="celebration" aria-live="polite"><div className="celebration-word">YAHTZEE!</div>{Array.from({length:52},(_,i)=><span key={i} className="confetti" style={{left:`${(i*37)%101}%`,background:['#dcf0a5','#edc965','#83b8a0','#ffffff','#d7a877'][i%5],animationDelay:`${(i%9)*.05}s`,'--drift':`${((i*29)%280)-140}px`,transform:`rotate(${i*20}deg)`} as CSSProperties}/>)}</div>}
 </div>
}
function HistoryCard({game}:{game:Game}){const sorted=[...game.sheets].sort((a,b)=>totals(b.scores,b.bonus).total-totals(a.scores,a.bonus).total);const top=sorted[0],high=top?totals(top.scores,top.bonus).total:0,winners=sorted.filter(s=>totals(s.scores,s.bonus).total===high);return <details className="history-card"><summary><div><h3>{fmtTime(game.started_at)} <span style={{fontWeight:400,color:'#91a095',margin:'0 5px'}}>·</span> {game.sheets.length} {game.sheets.length===1?'player':'players'}</h3><p>{game.ended_at?`${Math.max(1,Math.round((game.ended_at-game.started_at)/60000))} min · ${sorted.length===1?'Solo game':winners.length>1?'Shared victory':`${top?.name} won`}`:'Unfinished game · not counted in wins'}</p><div className="history-players">{sorted.map(s=><Avatar key={s.player_id} name={s.name}/>)}</div></div><span className="inline"><span className={`pill ${game.ended_at?'':'neutral'}`}>{game.ended_at?<Trophy size={13}/>:<Flag size={13}/>} {game.ended_at?`${high} pts`:'Unfinished'}</span><ChevronDown size={16}/></span></summary><div className="history-results">{sorted.map((s,i)=><div className="player-row" key={s.player_id}><span className="player-rank">{i+1}</span><Avatar name={s.name}/><span className="player-name">{s.name}<small>{s.completed_at?'Finished':`${totals(s.scores,s.bonus).filled} of 13 scored`}</small></span><span className="player-score">{totals(s.scores,s.bonus).total}</span></div>)}<div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Category</TableHead>{sorted.map(s=><TableHead key={s.player_id}>{s.name}</TableHead>)}</TableRow></TableHeader><TableBody>{categories.map(c=><TableRow key={c.id}><TableCell>{c.name}</TableCell>{sorted.map(s=><TableCell key={s.player_id}>{s.scores[c.id]??'—'}</TableCell>)}</TableRow>)}<TableRow><TableCell>Upper bonus</TableCell>{sorted.map(s=><TableCell key={s.player_id}>{totals(s.scores,s.bonus).upperBonus}</TableCell>)}</TableRow><TableRow><TableCell>Yahtzee bonus</TableCell>{sorted.map(s=><TableCell key={s.player_id}>{s.bonus*100}</TableCell>)}</TableRow><TableRow><TableCell><strong>Total</strong></TableCell>{sorted.map(s=><TableCell key={s.player_id}><strong>{totals(s.scores,s.bonus).total}</strong></TableCell>)}</TableRow></TableBody></Table></div></div></details>}
