import {execFileSync} from 'node:child_process';
import {mkdirSync,cpSync,copyFileSync,readdirSync,writeFileSync} from 'node:fs';
const project=process.cwd();
execFileSync('node',['node_modules/vite/bin/vite.js','build','--config','lan/vite.config.mts'],{stdio:'inherit'});
execFileSync(process.execPath,['node_modules/esbuild/bin/esbuild','lib/server.ts','--bundle','--platform=node','--format=esm','--outfile=.local-build/server-core.mjs'],{stdio:'inherit'});
for(const name of ['start.mjs','README.txt','Start-Windows.cmd'])copyFileSync('lan/'+name,'.local-build/'+name);
for(const name of ['favicon.svg','manifest.webmanifest','apple-touch-icon.png'])copyFileSync('public/'+name,'.local-build/public/'+name);
cpSync('public/icons','.local-build/public/icons',{recursive:true});
mkdirSync('.local-build/migrations',{recursive:true});
for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')))copyFileSync('drizzle/'+name,'.local-build/migrations/'+name);
execFileSync(process.env.YAHTZEE_PYTHON||'python',['-c',"import zipfile,pathlib; root=pathlib.Path('.local-build'); z=zipfile.ZipFile('public/yahtzee-local.zip','w',zipfile.ZIP_DEFLATED); [z.write(p,'yahtzee-table/'+str(p.relative_to(root))) for p in sorted(root.rglob('*')) if p.is_file() and 'sqlite' not in p.name]; z.close()"],{stdio:'inherit'});
